/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness — process up (NFR-14, ARB-04) */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness — includes DB connectivity (NFR-15)
     * @description Deploy gates and load-balancer checks target this endpoint. False during boot (before Mongo connect + integrity check) and after SIGTERM (drain) per BEA §8.
     */
    get: operations['getReady'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Authenticate; set refresh cookie; return access token + profile (FR-AUTH-01/04, UC-01)
     * @description Failure counter and lockout per BR-33; success resets the counter, stamps lastLoginAt, records a security event. Errors stay generic — the password policy is never revealed on this route (AAD §2).
     */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rotate the refresh token; issue a new access token (FR-AUTH-02/06)
     * @description Cookie-authenticated (no body). Reuse of a rotated token revokes the entire session family and records a security event (BR-35). Clients single-flight this call (ARB-03).
     */
    post: operations['refreshSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Revoke the current refresh token; clear the cookie (FR-AUTH-03)
     * @description Idempotent — revoking an already-revoked/unknown token still succeeds.
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Complete an Admin-initiated reset (FR-AUTH-05, UC-03)
     * @description Token is single-use, 30-min expiry, hashed at rest; success revokes all prior sessions and clears mustChangePassword.
     */
    post: operations['resetPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change own password (FR-USER-05)
     * @description Current password required and verified; revokes all OTHER sessions. One of the three calls a mustChangePassword session may make (AAD §2).
     */
    post: operations['changePassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List users (FR-USER-02, §9.12) — Admin */
    get: operations['listUsers'];
    put?: never;
    /**
     * Provision a user with a temporary password (FR-USER-01, BR-31) — Admin
     * @description Created accounts carry mustChangePassword=true. Self-registration does not exist.
     */
    post: operations['createUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Own profile (§9.14) — Any */
    get: operations['getOwnProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update own name — Any. Role/status/email changes are not possible on this route. */
    patch: operations['updateOwnProfile'];
    trace?: never;
  };
  '/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /** Single user — Admin */
    get: operations['getUser'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update name/role/isActive (FR-USER-02/03/04) — Admin
     * @description Boundary T6 — atomic active-admin count + change + session revocation + audit entry in one transaction (BR-30). Demotion/deactivation revokes all target sessions immediately.
     */
    patch: operations['updateUser'];
    trace?: never;
  };
  '/users/{id}/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Issue a single-use reset link (FR-AUTH-05, UC-03) — Admin
     * @description Revokes the target's sessions at issue; returns the link for out-of-band delivery (AS-6). Token is hashed at rest, 30-min expiry.
     */
    post: operations['issueResetLink'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description The CLOSED set of codes this API may emit — SRS §16.3 catalog plus the three documented APR-01 extensions (DUPLICATE_EMAIL, PRODUCT_NOT_EMPTY, PRODUCT_HAS_HISTORY). 05 §6.2.
     * @enum {string}
     */
    ErrorCode:
      | 'VALIDATION_ERROR'
      | 'UNAUTHORIZED'
      | 'ACCOUNT_DEACTIVATED'
      | 'FORBIDDEN'
      | 'NOT_FOUND'
      | 'DUPLICATE_SKU'
      | 'DUPLICATE_BARCODE'
      | 'DUPLICATE_EMAIL'
      | 'INSUFFICIENT_STOCK'
      | 'STALE_WRITE'
      | 'LAST_ADMIN'
      | 'PRODUCT_ARCHIVED'
      | 'PRODUCT_NOT_EMPTY'
      | 'PRODUCT_HAS_HISTORY'
      | 'CATEGORY_IN_USE'
      | 'INVALID_BARCODE'
      | 'IDEMPOTENCY_CONFLICT'
      | 'ACCOUNT_LOCKED'
      | 'RATE_LIMITED'
      | 'INTERNAL_ERROR'
      | 'SERVICE_UNAVAILABLE';
    /** @description VALIDATION_ERROR uses details = array of these (05 §6.1). */
    ValidationErrorDetail: {
      field: string;
      message: string;
    };
    /** @description The single error envelope every non-2xx JSON response uses (SRS §16.2, 05 §6.1). */
    ErrorEnvelope: {
      error: {
        code: components['schemas']['ErrorCode'];
        /** @description Human-readable; the frontend maps code → message via its own table (05 §6.2). */
        message: string;
        /** @description Optional, code-specific payload (e.g. available/requested for INSUFFICIENT_STOCK). */
        details?: unknown;
        /** @description Echoes X-Correlation-Id — surfaced in error toasts (NFR-23). */
        correlationId: string;
      };
    };
    /** @description List-envelope metadata (05 §5, FR-SRCH-03). Every list endpoint returns { data: [...], ...PaginationMeta }; data item types are per-endpoint. */
    PaginationMeta: {
      page: number;
      limit: number;
      totalItems: number;
      totalPages: number;
    };
    /**
     * @description The two operator roles (SRS §5 matrix).
     * @enum {string}
     */
    Role: 'ADMIN' | 'STAFF';
    /** @description 05 §15.1 — non-empty password only; policy never applied at login (AAD §2). */
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    /** @description 05 §15.7 — BR-32 policy applies to newPassword. */
    ResetPasswordRequest: {
      token: string;
      newPassword: string;
    };
    /** @description 05 §15.7 — new ≠ current; BR-32 policy on newPassword. */
    ChangePasswordRequest: {
      currentPassword: string;
      newPassword: string;
    };
    /** @description 05 §15.6 — temporary password per BR-32; mustChangePassword is server-set. */
    UserCreateRequest: {
      name: string;
      /** Format: email */
      email: string;
      role: components['schemas']['Role'];
      temporaryPassword: string;
    };
    /** @description Any of name/role/isActive — nothing else (05 §15.6). At least one required. */
    UserUpdateRequest: {
      name?: string;
      role?: components['schemas']['Role'];
      isActive?: boolean;
    };
    /** @description Admin-facing user row (05 §7.2) — never carries credential fields (SEC-02). */
    User: {
      id: string;
      name: string;
      /** Format: email */
      email: string;
      role: components['schemas']['Role'];
      isActive: boolean;
      /**
       * Format: date-time
       * @description Absent when the user has never logged in (optional-sparse rule, 05 §2).
       */
      lastLoginAt?: string;
      /** Format: date-time */
      createdAt: string;
    };
    /** @description GET/PATCH /users/me shape (05 §7.2). */
    OwnProfile: {
      id: string;
      name: string;
      /** Format: email */
      email: string;
      role: components['schemas']['Role'];
      mustChangePassword: boolean;
      /** Format: date-time */
      lastLoginAt?: string;
    };
    /** @description Out-of-band reset link (AS-6) — the operator delivers it themselves. */
    ResetLinkResponse: {
      /** Format: uri */
      resetLink: string;
      /** Format: date-time */
      expiresAt: string;
    };
    /** @description The 05 §7.1 session user block — never carries credential fields (SEC-02). */
    SessionUser: {
      id: string;
      name: string;
      /** Format: email */
      email: string;
      role: components['schemas']['Role'];
      mustChangePassword: boolean;
    };
    /** @description FCM-01 (RATIFIED 2026-07-23): read-only display constants in the session payload — Staff has no other approved endpoint for them (GET /settings stays Admin-only). Additive, EXT-01-compliant; exposes no settings management. AAD §12 · SMA §5. */
    SessionSettings: {
      /** @description ISO 4217 code — feeds lib/formatters. */
      systemCurrency: string;
      /** @description Large-movement confirm threshold (BR-15) for the movement dialogs. */
      movementWarningThreshold: number;
    };
    /** @description Login/refresh 200 — access token + profile + FCM-01 display constants. */
    SessionResponse: {
      /** @description JWT HS256, 15-min TTL, payload sub/role/iat/exp only (SEC-01). */
      accessToken: string;
      user: components['schemas']['SessionUser'];
      settings: components['schemas']['SessionSettings'];
    };
    HealthStatus: {
      /** @enum {string} */
      status: 'ok';
    };
    ReadyStatus: {
      /** @enum {string} */
      status: 'ready';
    };
  };
  responses: {
    /** @description Request failed schema validation before the controller ran (05 §1). */
    ValidationError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Missing/invalid token, or account deactivated (UNAUTHORIZED | ACCOUNT_DEACTIVATED). */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Role insufficient per the §5 permission matrix (FORBIDDEN). */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Resource not found (NOT_FOUND). */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Rate limit exceeded (RATE_LIMITED, SEC-04). */
    RateLimited: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Opaque internal error — correlation ID only, no internals (SEC-12). */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description DB down / not ready; carries Retry-After (NFR-20). */
    ServiceUnavailable: {
      headers: {
        'Retry-After': components['headers']['RetryAfter'];
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
  };
  parameters: {
    /** @description 1-based page number (05 §5). */
    page: number;
    /** @description Page size — hard cap 100; values above cap → VALIDATION_ERROR (NFR-10). */
    limit: number;
    /** @description Sort field — sortable fields enumerated per endpoint; unknown → VALIDATION_ERROR. */
    sort: string;
    /** @description Sort direction companion to sort (APD-01). Default desc. */
    order: 'asc' | 'desc';
  };
  requestBodies: never;
  headers: {
    /** @description Correlation ID echoed on every response (NFR-23, 05 §1). */
    XCorrelationId: string;
    /** @description Seconds to wait before retrying (NFR-20). */
    RetryAfter: number;
  };
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Process is up. No auth, no rate limit, no business data. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthStatus'];
        };
      };
    };
  };
  getReady: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ready to serve traffic. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReadyStatus'];
        };
      };
      /** @description Not ready (DB down / booting / draining). Carries Retry-After (NFR-20). */
      503: {
        headers: {
          'Retry-After': components['headers']['RetryAfter'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Session established. Also sets the rotating refresh cookie (httpOnly · Secure · SameSite=Strict · Path=/api/v1/auth). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionResponse'];
        };
      };
      400: components['responses']['ValidationError'];
      /** @description Bad credentials (generic — UNAUTHORIZED) or ACCOUNT_DEACTIVATED. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description ACCOUNT_LOCKED — 5 consecutive failures → 15-min lock (BR-33). */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      429: components['responses']['RateLimited'];
    };
  };
  refreshSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Rotated session + new refresh Set-Cookie. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionResponse'];
        };
      };
      /** @description Missing/expired/revoked/reused token (UNAUTHORIZED). */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session revoked; expired Set-Cookie returned. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['Unauthorized'];
    };
  };
  resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordRequest'];
      };
    };
    responses: {
      /** @description Password installed; all prior sessions revoked. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['ValidationError'];
      /** @description Invalid/expired/used token (UNAUTHORIZED). */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      429: components['responses']['RateLimited'];
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest'];
      };
    };
    responses: {
      /** @description Password changed; other sessions revoked. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['ValidationError'];
      /** @description Wrong current password, or missing/invalid access token. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  listUsers: {
    parameters: {
      query?: {
        /** @description 1-based page number (05 §5). */
        page?: components['parameters']['page'];
        /** @description Page size — hard cap 100; values above cap → VALIDATION_ERROR (NFR-10). */
        limit?: components['parameters']['limit'];
        role?: components['schemas']['Role'];
        isActive?: boolean;
        /** @description Name/email partial match, ≤ 120 chars. */
        search?: string;
        sort?: 'name' | 'email' | 'createdAt' | 'lastLoginAt';
        /** @description Sort direction companion to sort (APD-01). Default desc. */
        order?: components['parameters']['order'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List envelope of user rows. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginationMeta'] & {
            data: components['schemas']['User'][];
          };
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  createUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCreateRequest'];
      };
    };
    responses: {
      /** @description Created user (no credential fields, SEC-02). */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      /** @description DUPLICATE_EMAIL — SRS §12.2 mandated 409, unique-index-backed (race-safe). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  getOwnProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Own profile. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OwnProfile'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  updateOwnProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
        };
      };
    };
    responses: {
      /** @description Updated profile (change audited). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OwnProfile'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
    };
  };
  getUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User (no credential fields). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  updateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdateRequest'];
      };
    };
    responses: {
      /** @description Updated user. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      /** @description LAST_ADMIN — the last active Admin is unviolable (BR-30). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  issueResetLink: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Reset link + expiry. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ResetLinkResponse'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
}
