/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness — process up (NFR-14, ARB-04) */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness — includes DB connectivity (NFR-15)
     * @description Deploy gates and load-balancer checks target this endpoint. False during boot (before Mongo connect + integrity check) and after SIGTERM (drain) per BEA §8.
     */
    get: operations['getReady'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description The CLOSED set of codes this API may emit — SRS §16.3 catalog plus the three documented APR-01 extensions (DUPLICATE_EMAIL, PRODUCT_NOT_EMPTY, PRODUCT_HAS_HISTORY). 05 §6.2.
     * @enum {string}
     */
    ErrorCode:
      | 'VALIDATION_ERROR'
      | 'UNAUTHORIZED'
      | 'ACCOUNT_DEACTIVATED'
      | 'FORBIDDEN'
      | 'NOT_FOUND'
      | 'DUPLICATE_SKU'
      | 'DUPLICATE_BARCODE'
      | 'DUPLICATE_EMAIL'
      | 'INSUFFICIENT_STOCK'
      | 'STALE_WRITE'
      | 'LAST_ADMIN'
      | 'PRODUCT_ARCHIVED'
      | 'PRODUCT_NOT_EMPTY'
      | 'PRODUCT_HAS_HISTORY'
      | 'CATEGORY_IN_USE'
      | 'INVALID_BARCODE'
      | 'IDEMPOTENCY_CONFLICT'
      | 'ACCOUNT_LOCKED'
      | 'RATE_LIMITED'
      | 'INTERNAL_ERROR'
      | 'SERVICE_UNAVAILABLE';
    /** @description VALIDATION_ERROR uses details = array of these (05 §6.1). */
    ValidationErrorDetail: {
      field: string;
      message: string;
    };
    /** @description The single error envelope every non-2xx JSON response uses (SRS §16.2, 05 §6.1). */
    ErrorEnvelope: {
      error: {
        code: components['schemas']['ErrorCode'];
        /** @description Human-readable; the frontend maps code → message via its own table (05 §6.2). */
        message: string;
        /** @description Optional, code-specific payload (e.g. available/requested for INSUFFICIENT_STOCK). */
        details?: unknown;
        /** @description Echoes X-Correlation-Id — surfaced in error toasts (NFR-23). */
        correlationId: string;
      };
    };
    /** @description List-envelope metadata (05 §5, FR-SRCH-03). Every list endpoint returns { data: [...], ...PaginationMeta }; data item types are per-endpoint. */
    PaginationMeta: {
      page: number;
      limit: number;
      totalItems: number;
      totalPages: number;
    };
    HealthStatus: {
      /** @enum {string} */
      status: 'ok';
    };
    ReadyStatus: {
      /** @enum {string} */
      status: 'ready';
    };
  };
  responses: {
    /** @description Request failed schema validation before the controller ran (05 §1). */
    ValidationError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Missing/invalid token, or account deactivated (UNAUTHORIZED | ACCOUNT_DEACTIVATED). */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Role insufficient per the §5 permission matrix (FORBIDDEN). */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Resource not found (NOT_FOUND). */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Rate limit exceeded (RATE_LIMITED, SEC-04). */
    RateLimited: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Opaque internal error — correlation ID only, no internals (SEC-12). */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description DB down / not ready; carries Retry-After (NFR-20). */
    ServiceUnavailable: {
      headers: {
        'Retry-After': components['headers']['RetryAfter'];
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
  };
  parameters: {
    /** @description 1-based page number (05 §5). */
    page: number;
    /** @description Page size — hard cap 100; values above cap → VALIDATION_ERROR (NFR-10). */
    limit: number;
    /** @description Sort field — sortable fields enumerated per endpoint; unknown → VALIDATION_ERROR. */
    sort: string;
    /** @description Sort direction companion to sort (APD-01). Default desc. */
    order: 'asc' | 'desc';
  };
  requestBodies: never;
  headers: {
    /** @description Correlation ID echoed on every response (NFR-23, 05 §1). */
    XCorrelationId: string;
    /** @description Seconds to wait before retrying (NFR-20). */
    RetryAfter: number;
  };
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Process is up. No auth, no rate limit, no business data. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthStatus'];
        };
      };
    };
  };
  getReady: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ready to serve traffic. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReadyStatus'];
        };
      };
      /** @description Not ready (DB down / booting / draining). Carries Retry-After (NFR-20). */
      503: {
        headers: {
          'Retry-After': components['headers']['RetryAfter'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
}
