/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness — process up (NFR-14, ARB-04) */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness — includes DB connectivity (NFR-15)
     * @description Deploy gates and load-balancer checks target this endpoint. False during boot (before Mongo connect + integrity check) and after SIGTERM (drain) per BEA §8.
     */
    get: operations['getReady'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/signup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Public self-service signup — create an organization + first Admin (SaaS)
     * @description Provisions a new tenant (organization + its first Admin owner + per-tenant settings + Uncategorized category) atomically, then returns a full session (the owner is logged straight in). Email is globally unique across all tenants — a collision is a 409 DUPLICATE_EMAIL. Strict-limited.
     */
    post: operations['signup'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Authenticate; set refresh cookie; return access token + profile (FR-AUTH-01/04, UC-01)
     * @description Failure counter and lockout per BR-33; success resets the counter, stamps lastLoginAt, records a security event. Errors stay generic — the password policy is never revealed on this route (AAD §2).
     */
    post: operations['login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/google': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sign in / sign up with Google (GIS ID-token → session)
     * @description Verifies a Google Identity Services ID token (google-auth-library) and resolves-or-provisions by VERIFIED email: an existing account is linked (googleSub attached) and logged in; an unknown email provisions a new password-less workspace. Backs both the "Sign in" and "Sign up with Google" buttons. Unverified Google email is rejected (401).
     */
    post: operations['googleAuth'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rotate the refresh token; issue a new access token (FR-AUTH-02/06)
     * @description Cookie-authenticated (no body). Reuse of a rotated token revokes the entire session family and records a security event (BR-35). Clients single-flight this call (ARB-03).
     */
    post: operations['refreshSession'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Revoke the current refresh token; clear the cookie (FR-AUTH-03)
     * @description Idempotent — revoking an already-revoked/unknown token still succeeds.
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Complete an Admin-initiated reset (FR-AUTH-05, UC-03)
     * @description Token is single-use, 30-min expiry, hashed at rest; success revokes all prior sessions and clears mustChangePassword.
     */
    post: operations['resetPassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change own password (FR-USER-05)
     * @description Current password required and verified; revokes all OTHER sessions. One of the three calls a mustChangePassword session may make (AAD §2).
     */
    post: operations['changePassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List users (FR-USER-02, §9.12) — Admin */
    get: operations['listUsers'];
    put?: never;
    /**
     * Provision a user with a temporary password (FR-USER-01, BR-31) — Admin
     * @description Created accounts carry mustChangePassword=true. Self-registration does not exist.
     */
    post: operations['createUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Own profile (§9.14) — Any */
    get: operations['getOwnProfile'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update own name — Any. Role/status/email changes are not possible on this route. */
    patch: operations['updateOwnProfile'];
    trace?: never;
  };
  '/users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /** Single user — Admin */
    get: operations['getUser'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update name/role/isActive (FR-USER-02/03/04) — Admin
     * @description Boundary T6 — atomic active-admin count + change + session revocation + audit entry in one transaction (BR-30). Demotion/deactivation revokes all target sessions immediately.
     */
    patch: operations['updateUser'];
    trace?: never;
  };
  '/users/{id}/reset-password': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Issue a single-use reset link (FR-AUTH-05, UC-03) — Admin
     * @description Revokes the target's sessions at issue; returns the link for out-of-band delivery (AS-6). Token is hashed at rest, 30-min expiry.
     */
    post: operations['issueResetLink'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List categories (FR-CAT-03, §7.4) — Any */
    get: operations['listCategories'];
    put?: never;
    /**
     * Create a category (FR-CAT-01, BR-26) — Admin
     * @description Name is unique case-insensitive via the collation index. A duplicate — including a concurrent-create race — maps to VALIDATION_ERROR, NOT a 409 (APR-08: no SRS §16.3 409 mandate exists for category names).
     */
    post: operations['createCategory'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/categories/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /** Single category — Any */
    get: operations['getCategory'];
    put?: never;
    post?: never;
    /**
     * Delete a category, optionally reassigning its products (FR-CAT-02, BR-27/28) — Admin
     * @description Boundary T5 — assert/reassign references + delete + audit, one atomic transaction. Blocked while any product (active OR archived) references it and no reassignment target is supplied → 409 CATEGORY_IN_USE. The system category is undeletable → VALIDATION_ERROR.
     */
    delete: operations['deleteCategory'];
    options?: never;
    head?: never;
    /**
     * Update name/description (FR-CAT-01, BR-26) — Admin
     * @description Replaces name + description (an omitted description unsets). The system category is unmodifiable (BR-28) — the attempt returns VALIDATION_ERROR.
     */
    patch: operations['updateCategory'];
    trace?: never;
  };
  '/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List products (FR-PROD-05, §7.3) — Any
     * @description Row projections (no image arrays, NFR-05). `archived` is an Admin-only filter (APD-02) — a Staff request carrying it is 403; omitted ⇒ active only.
     */
    get: operations['listProducts'];
    put?: never;
    /**
     * Create a product (FR-PROD-01, BR-01…10) — Admin
     * @description Boundary T2 — insert product + (non-zero initial stock) an INITIAL ledger row, one atomic transaction, so quantity == Σ ledger from creation. Blank SKU auto-generates from the category prefix (BR-04).
     */
    post: operations['createProduct'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/products/lookup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Look up a product by barcode then SKU (BR-06/07) — Any
     * @description Barcode (primary) then SKU (fallback). An archived product is reported AS archived, never as not-found (BR-07). A malformed payload is 422 INVALID_BARCODE (BR-16), not a 400.
     */
    get: operations['lookupProduct'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/products/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    /** Single product — Any */
    get: operations['getProduct'];
    put?: never;
    post?: never;
    /**
     * Hard delete a product with zero ledger history (BR-23) — Admin
     * @description Boundary T4 — assert zero transactions + delete + audit, atomic. Any product with stock history (an INITIAL row or movements) can only be archived → 409 PRODUCT_HAS_HISTORY.
     */
    delete: operations['deleteProduct'];
    options?: never;
    head?: never;
    /**
     * Update catalog fields with optimistic concurrency (BR-24) — Admin
     * @description Carries `version`; a mismatch is 409 STALE_WRITE. SKU is immutable (BR-03) and quantity is MovementService-only (BR-17) — neither is accepted here.
     */
    patch: operations['updateProduct'];
    trace?: never;
  };
  '/products/{id}/archive': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Archive a product (requires zero stock, BR-22) — Admin
     * @description Boundary T3 — the quantity == 0 predicate is checked inside the write (a concurrent movement aborts one op).
     */
    post: operations['archiveProduct'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/products/{id}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore an archived product (FR-PROD-04) — Admin */
    post: operations['restoreProduct'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/inventory/movements': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Record a stock movement (BR-11…20) — Any (STOCK_IN/OUT) · Admin (ADJUSTMENT)
     * @description The load-bearing ledger endpoint (ARC §3.2). Executes Boundary T1 — conditional findOneAndUpdate (isArchived:false; quantity ≥ requested for negatives) + Transaction insert, one majority transaction (A-1), with bounded transient-conflict retry. The Idempotency-Key header is required (05 §4): a replay with the identical payload returns the original outcome (A-4), the same key with a different payload is 422 IDEMPOTENCY_CONFLICT. The ONE validate-before-authorize route (AAD §5.2) — a Staff-submitted ADJUSTMENT is 403.
     */
    post: operations['recordMovement'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/transactions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List the stock ledger (FR-TXN-01…03) — Any
     * @description The append-only Stock Ledger (F7 tab). Rows carry product + user display labels; an archived-product row sets productArchived (EC-16 badge) and is hidden unless includeArchived=true — or a specific productId is filtered (explicit intent wins). Paginated (05 §5 envelope), createdAt-desc.
     */
    get: operations['listTransactions'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/audit-logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List the audit trail (FR-TXN-04/05) — Admin
     * @description Paginated audit trail — entity diffs + security events. entityLabel (DN-4) renders entries after hard deletes. Append-only; no mutation route exists (DES-1). Filterable by entity type / entity / actor / ordered date range.
     */
    get: operations['listAuditLogs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The single cached dashboard aggregate (FR-DASH-01…04) — Any
     * @description Every dashboard metric and both chart series in ONE call (FR-DASH-03), served from a per-instance cache (30–60 s TTL, A-2). `asOf` reports when the served snapshot was computed — under a cache hit it can lag by up to one TTL, the stated staleness bound (BR-25). Totals exclude archived products; recent rows and chart series span all products.
     */
    get: operations['getDashboardSummary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reports/inventory': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Inventory Summary report (FR-RPT-01) — Any
     * @description Per active product: SKU, name, category, quantity, current cost, and line value (cost × quantity), with a totals row. Filter by category and derived stock status. Values use CURRENT cost (AS-17).
     */
    get: operations['getInventoryReport'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reports/low-stock': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Low Stock report (FR-RPT-02) — Any
     * @description Active products at or below their threshold, with threshold, quantity, and shortage.
     */
    get: operations['getLowStockReport'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reports/transactions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Transaction History report (FR-RPT-03, BR-40) — Any
     * @description Ledger-derived movements over a MANDATORY date range (both bounds required, span ≤ 366 days). Re-running a past period is byte-identical (BR-40). Rows are the ledger row shape.
     */
    get: operations['getTransactionsReport'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reports/product-performance': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Product Performance report (FR-RPT-04) — Any
     * @description Per-product in/out/net movement totals over a MANDATORY date range (span ≤ 366 days), ledger-derived (BR-40), with an overall totals row.
     */
    get: operations['getProductPerformanceReport'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reports/consistency': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ledger Consistency report (FR-RPT-05, BR-18) — Admin
     * @description Per-product reconciliation: ledger sum (Σ quantityChange) vs the materialized quantity, drift flagged. Snapshot-consistent (ARB-05).
     */
    get: operations['getConsistencyReport'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/reports/{name}/export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Stream a report as CSV (FR-RPT-06) — Admin
     * @description Streams `text/csv` of the FULL filtered dataset for the named report (page/limit ignored, APR-06). Admin-only — Staff receive 403 at the API. Same filters as the named report. The stream writes rows only after a successful first batch; a mid-stream failure destroys the connection rather than emitting a truncated-but-complete-looking file (ERR §7).
     */
    get: operations['exportReport'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read the settings singleton (BR-41) — Admin
     * @description Admin-only; Staff reads these constants from the session payload (FCM-01), never here.
     */
    get: operations['getSettings'];
    /**
     * Update the settings singleton (BR-41, audited) — Admin
     * @description Full-object replace of the singleton, in place. defaultLowStockThreshold changes apply to NEW products only (DN-3) — existing products keep their copied value. Changes are audited (entityType SETTINGS).
     */
    put: operations['updateSettings'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/upload/signature': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sign a Cloudinary upload scoped to ims/prod (SEC-08, BR-36) — Admin
     * @description Returns signed params; the browser uploads directly to Cloudinary — image bytes never transit this API. Type/size are validated before signing.
     */
    post: operations['createUploadSignature'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/upload/{publicId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Destroy an uploaded asset (BR-38) — Admin
     * @description The publicId contains `/` and MUST be percent-encoded. Folder-scoped (APR-03): a publicId outside the app's ims/prod folder is 403 and can never be destroyed here.
     */
    delete: operations['destroyUpload'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/chat': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Ask the read-only AI Inventory Assistant a question — Any
     * @description One question in, one deterministic answer out. An LLM is used for exactly one thing — turning the sentence into a validated intent + slots — after which a hand-written handler queries existing services and a TEMPLATE renders the reply. No generated text ever contains a number, so a stock figure cannot be hallucinated. Read-only: there is no write path.
     *     Mounted only when CHAT_ENABLED is true; otherwise the route 404s and `settings.chatEnabled` on the session payload is false so the client hides the entry point. Provider outage, timeout or quota exhaustion is a 503 SERVICE_UNAVAILABLE with Retry-After — never a 500 and never a hang.
     */
    post: operations['askAssistant'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/chat/feedback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Rate an answer thumbs up/down — Any
     * @description Recorded as a LOG EVENT keyed on the answer's `correlationId`, which joins it to that message's structured record. No collection, no CRUD — thumbs are the cheapest labelled data available for improving intent classification.
     */
    post: operations['rateAssistantAnswer'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * @description The CLOSED set of codes this API may emit — SRS §16.3 catalog plus the three documented APR-01 extensions (DUPLICATE_EMAIL, PRODUCT_NOT_EMPTY, PRODUCT_HAS_HISTORY). 05 §6.2.
     * @enum {string}
     */
    ErrorCode:
      | 'VALIDATION_ERROR'
      | 'UNAUTHORIZED'
      | 'ACCOUNT_DEACTIVATED'
      | 'FORBIDDEN'
      | 'NOT_FOUND'
      | 'DUPLICATE_SKU'
      | 'DUPLICATE_BARCODE'
      | 'DUPLICATE_EMAIL'
      | 'INSUFFICIENT_STOCK'
      | 'STALE_WRITE'
      | 'LAST_ADMIN'
      | 'PRODUCT_ARCHIVED'
      | 'PRODUCT_NOT_EMPTY'
      | 'PRODUCT_HAS_HISTORY'
      | 'CATEGORY_IN_USE'
      | 'INVALID_BARCODE'
      | 'IDEMPOTENCY_CONFLICT'
      | 'ACCOUNT_LOCKED'
      | 'RATE_LIMITED'
      | 'INTERNAL_ERROR'
      | 'SERVICE_UNAVAILABLE';
    /** @description VALIDATION_ERROR uses details = array of these (05 §6.1). */
    ValidationErrorDetail: {
      field: string;
      message: string;
    };
    /** @description The single error envelope every non-2xx JSON response uses (SRS §16.2, 05 §6.1). */
    ErrorEnvelope: {
      error: {
        code: components['schemas']['ErrorCode'];
        /** @description Human-readable; the frontend maps code → message via its own table (05 §6.2). */
        message: string;
        /** @description Optional, code-specific payload (e.g. available/requested for INSUFFICIENT_STOCK). */
        details?: unknown;
        /** @description Echoes X-Correlation-Id — surfaced in error toasts (NFR-23). */
        correlationId: string;
      };
    };
    /** @description List-envelope metadata (05 §5, FR-SRCH-03). Every list endpoint returns { data: [...], ...PaginationMeta }; data item types are per-endpoint. */
    PaginationMeta: {
      page: number;
      limit: number;
      totalItems: number;
      totalPages: number;
    };
    /**
     * @description The two operator roles (SRS §5 matrix).
     * @enum {string}
     */
    Role: 'ADMIN' | 'STAFF';
    /** @description Public self-service signup (SaaS). BR-32 password policy applies (this is the account's first password). email is globally unique across tenants. */
    SignupRequest: {
      organizationName: string;
      name: string;
      /** Format: email */
      email: string;
      password: string;
    };
    /** @description 05 §15.1 — non-empty password only; policy never applied at login (AAD §2). */
    LoginRequest: {
      /** Format: email */
      email: string;
      password: string;
    };
    /** @description Google Identity Services ID token; verified server-side. */
    GoogleAuthRequest: {
      idToken: string;
    };
    /** @description 05 §15.7 — BR-32 policy applies to newPassword. */
    ResetPasswordRequest: {
      token: string;
      newPassword: string;
    };
    /** @description 05 §15.7 — new ≠ current; BR-32 policy on newPassword. */
    ChangePasswordRequest: {
      currentPassword: string;
      newPassword: string;
    };
    /** @description 05 §15.6 — temporary password per BR-32; mustChangePassword is server-set. */
    UserCreateRequest: {
      name: string;
      /** Format: email */
      email: string;
      role: components['schemas']['Role'];
      temporaryPassword: string;
    };
    /** @description Any of name/role/isActive — nothing else (05 §15.6). At least one required. */
    UserUpdateRequest: {
      name?: string;
      role?: components['schemas']['Role'];
      isActive?: boolean;
    };
    /** @description Admin-facing user row (05 §7.2) — never carries credential fields (SEC-02). */
    User: {
      id: string;
      name: string;
      /** Format: email */
      email: string;
      role: components['schemas']['Role'];
      isActive: boolean;
      /**
       * Format: date-time
       * @description Absent when the user has never logged in (optional-sparse rule, 05 §2).
       */
      lastLoginAt?: string;
      /** Format: date-time */
      createdAt: string;
    };
    /** @description GET/PATCH /users/me shape (05 §7.2). */
    OwnProfile: {
      id: string;
      name: string;
      /** Format: email */
      email: string;
      role: components['schemas']['Role'];
      mustChangePassword: boolean;
      /** Format: date-time */
      lastLoginAt?: string;
    };
    /** @description Out-of-band reset link (AS-6) — the operator delivers it themselves. */
    ResetLinkResponse: {
      /** Format: uri */
      resetLink: string;
      /** Format: date-time */
      expiresAt: string;
    };
    /** @description 05 §15.3 — POST and PATCH share this shape. name 2–60, unique case-insensitive (BR-26); description optional, ≤ 300 (blank → absent). isSystem is server-set and never accepted here (BR-28). */
    CategoryWriteRequest: {
      name: string;
      description?: string;
    };
    /** @description Category row (05 §7.4). productCount present only on ?withCounts=true. */
    Category: {
      id: string;
      name: string;
      /** @description Absent when unset (optional-sparse rule, 05 §2). */
      description?: string;
      /** @description true only for Uncategorized — undeletable and unmodifiable (BR-28). */
      isSystem: boolean;
      /** @description Products (active + archived) referencing this category; only on ?withCounts=true (§9.9). */
      productCount?: number;
    };
    /** @description 05 §7.9 — declares the intended upload so the server can reject disallowed type/size before signing (BR-36). */
    UploadSignatureRequest: {
      /** @enum {string} */
      contentType: 'image/jpeg' | 'image/png' | 'image/webp';
      /** @description Bytes; ≤ 5 MB. */
      size: number;
    };
    /** @description Signed params for a direct browser upload to Cloudinary. */
    UploadSignatureResponse: {
      signature: string;
      timestamp: number;
      apiKey: string;
      cloudName: string;
      /** @example ims/prod */
      folder: string;
    };
    /**
     * @description Derived from quantity vs lowStockThreshold (05 §2) — never stored.
     * @enum {string}
     */
    StockStatus: 'IN_STOCK' | 'LOW_STOCK' | 'OUT_OF_STOCK';
    /**
     * @description Decimal amount as a 2-dp string (DBR-05) — never a float on the wire.
     * @example 12.50
     */
    Money: string;
    /** @description Embedded supplier value object (DBD §2.3). */
    ProductSupplier: {
      name: string;
      contactName?: string;
      phone?: string;
      email?: string;
    };
    /** @description Cloudinary image reference (DBR-03 — exactly one primary when non-empty). Managed by F5's pipeline. */
    ProductImage: {
      publicId: string;
      /** Format: uri */
      url: string;
      isPrimary: boolean;
    };
    /** @description 05 §15.4 create. SKU optional (blank → auto BR-04). quantity is not accepted — `initialQuantity` seeds the ledger (BR-17). Money as strings. */
    ProductCreateRequest: {
      name: string;
      /** @description Optional; normalized to uppercase. Blank/omitted → auto-generated. */
      sku?: string;
      barcode?: string;
      categoryId: string;
      description?: string;
      costPrice: components['schemas']['Money'];
      sellingPrice: components['schemas']['Money'];
      /** @default 0 */
      initialQuantity: number;
      /** @description Absent → copied from Settings.defaultLowStockThreshold (DN-3). */
      lowStockThreshold?: number;
      supplier?: components['schemas']['ProductSupplier'];
      /** @description ≤ 5; exactly one primary when non-empty (DBR-03). publicIds must be from an F5 upload. */
      images?: components['schemas']['ProductImage'][];
    };
    /** @description 05 §15.4 update. MUST carry `version` (BR-24). Excludes sku (immutable, BR-03), quantity (BR-17), isArchived (lifecycle routes). At least one updatable field beyond version. */
    ProductUpdateRequest: {
      version: number;
      name?: string;
      barcode?: string;
      categoryId?: string;
      description?: string;
      costPrice?: components['schemas']['Money'];
      sellingPrice?: components['schemas']['Money'];
      lowStockThreshold?: number;
      supplier?: components['schemas']['ProductSupplier'];
      /** @description Replaces the whole set; removed publicIds are destroyed post-commit (BR-38). */
      images?: components['schemas']['ProductImage'][];
    };
    /** @description Full product (GET /products/:id · POST 201 · PATCH 200). Money as 2-dp strings. */
    Product: {
      id: string;
      name: string;
      sku: string;
      barcode?: string;
      description?: string;
      categoryId: string;
      /** @description Resolved category name (present when the server joined it). */
      categoryName?: string;
      quantity: number;
      lowStockThreshold: number;
      costPrice: components['schemas']['Money'];
      sellingPrice: components['schemas']['Money'];
      stockStatus: components['schemas']['StockStatus'];
      supplier?: components['schemas']['ProductSupplier'];
      images: components['schemas']['ProductImage'][];
      isArchived: boolean;
      version: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /** @description List row projection (GET /products) — no image array / no version (NFR-05). */
    ProductRow: {
      id: string;
      name: string;
      sku: string;
      barcode?: string;
      /**
       * Format: uri
       * @description Primary image URL, when present.
       */
      thumbnailUrl?: string;
      categoryName?: string;
      quantity: number;
      lowStockThreshold: number;
      stockStatus: components['schemas']['StockStatus'];
      costPrice: components['schemas']['Money'];
      sellingPrice: components['schemas']['Money'];
      isArchived: boolean;
    };
    /** @description Scanner-facing lookup result (GET /products/lookup, BR-06/07). */
    ProductLookup: {
      id: string;
      name: string;
      sku: string;
      barcode?: string;
      /** Format: uri */
      primaryImageUrl?: string;
      quantity: number;
      stockStatus: components['schemas']['StockStatus'];
      isArchived: boolean;
    };
    /** @description 05 §15.8 — full-object PUT; all three fields required (VAL §3.5). */
    SettingsUpdateRequest: {
      /** @description ISO 4217 code (3 uppercase letters). */
      currency: string;
      defaultLowStockThreshold: number;
      movementWarningThreshold: number;
    };
    /** @description The settings singleton (05 §7.10). Stored field names — `currency`, not the session `systemCurrency` alias. */
    Settings: {
      currency: string;
      defaultLowStockThreshold: number;
      movementWarningThreshold: number;
      /** Format: date-time */
      updatedAt: string;
    };
    /** @description The 05 §7.1 session user block — never carries credential fields (SEC-02). */
    SessionUser: {
      id: string;
      name: string;
      /** Format: email */
      email: string;
      role: components['schemas']['Role'];
      mustChangePassword: boolean;
    };
    ChatAskRequest: {
      /**
       * Format: uuid
       * @description Client-generated per chat session. A LOG FIELD only — Phase 1 has no memory and no Conversation collection. It costs one field and it is what makes question SEQUENCES recoverable, which is the highest-signal input for choosing the next intent to build.
       */
      conversationId: string;
      /** @description Bounded deliberately: without the cap a pasted block becomes a multi-kilobyte prompt, and token cost, latency and free-tier quota all scale with input that was never meant to be accepted. */
      question: string;
    };
    ChatFeedbackRequest: {
      /** @description The `correlationId` returned in the answer being rated. */
      correlationId: string;
      /** @enum {string} */
      rating: 'up' | 'down';
    };
    /** @description A discriminated union on `intent` — never `{summary, rows: unknown[]}`. Untyped rows would mean no contract, no generated client types, and per-intent rendering guesswork. Row shapes are the EXISTING ProductRow / TransactionRow shapes verbatim, so the client reuses its product table components and money stays a 2-dp string end to end. */
    ChatResponse:
      | components['schemas']['ChatProductLookupResult']
      | components['schemas']['ChatLowStockResult']
      | components['schemas']['ChatMovementHistoryResult']
      | components['schemas']['ChatUnsupportedResult']
      | components['schemas']['ChatClarifyResult'];
    ChatResultBase: {
      /** @description Rendered by a server-side template. Never model-generated. */
      summary: string;
      /** @description Clickable rephrase suggestions. Zero-result, too-many-result and unsupported replies all carry a recovery path — that is what turns a dead end into a rephrase. */
      examples: string[];
      /** @description Server-minted per message (NOT the request's X-Correlation-Id, which honours a client-supplied header and so could be spoofed or collided). This is the key POST /chat/feedback joins on. */
      correlationId: string;
    };
    ChatProductLookupResult: components['schemas']['ChatResultBase'] & {
      /** @enum {string} */
      intent: 'product_lookup';
      products: components['schemas']['ProductRow'][];
      /** @description Total MATCHES — `products` is capped at 10 and the summary says so. */
      totalCount: number;
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      intent: 'product_lookup';
    };
    ChatLowStockResult: components['schemas']['ChatResultBase'] & {
      /** @enum {string} */
      intent: 'low_stock';
      /** @description 0 < quantity <= lowStockThreshold. */
      low: components['schemas']['ProductRow'][];
      /** @description quantity == 0 — reported SEPARATELY because it is strictly more urgent, and folding it into one total loses that. */
      out: components['schemas']['ProductRow'][];
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      intent: 'low_stock';
    };
    ChatMovementHistoryResult: components['schemas']['ChatResultBase'] & {
      /** @enum {string} */
      intent: 'movement_history';
      product: components['schemas']['ProductRow'];
      movements: components['schemas']['TransactionRow'][];
      totalCount: number;
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      intent: 'movement_history';
    };
    ChatUnsupportedResult: components['schemas']['ChatResultBase'] & {
      /** @enum {string} */
      intent: 'unsupported';
      /** @description What the assistant CAN answer — a first-class reply, not an error. */
      capabilities: string[];
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      intent: 'unsupported';
    };
    ChatClarifyResult: components['schemas']['ChatResultBase'] & {
      /** @enum {string} */
      intent: 'clarify';
      /** @description Products a history question matched ambiguously. Listed rather than silently resolved — a history for the wrong product is indistinguishable on screen from the right one. */
      candidates: components['schemas']['ProductRow'][];
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      intent: 'clarify';
    };
    /** @description FCM-01 (RATIFIED 2026-07-23): read-only display constants in the session payload — Staff has no other approved endpoint for them (GET /settings stays Admin-only). Additive, EXT-01-compliant; exposes no settings management. AAD §12 · SMA §5. */
    SessionSettings: {
      /** @description ISO 4217 code — feeds lib/formatters. */
      systemCurrency: string;
      /** @description Large-movement confirm threshold (BR-15) for the movement dialogs. */
      movementWarningThreshold: number;
      /** @description CHAT_ENABLED — the AI assistant's kill switch. Environment-derived, not a tenant preference. The client hides the assistant entry point when false rather than offering a button that 404s. */
      chatEnabled: boolean;
    };
    /** @description Login/refresh 200 — access token + profile + FCM-01 display constants. */
    SessionResponse: {
      /** @description JWT HS256, 15-min TTL, payload sub/role/iat/exp only (SEC-01). */
      accessToken: string;
      user: components['schemas']['SessionUser'];
      settings: components['schemas']['SessionSettings'];
    };
    HealthStatus: {
      /** @enum {string} */
      status: 'ok';
    };
    ReadyStatus: {
      /** @enum {string} */
      status: 'ready';
    };
    /** @description POST /inventory/movements body (§3.4), discriminated on `type`. STOCK_IN/STOCK_OUT carry `quantity`; ADJUSTMENT carries `delta` XOR `countedQuantity` plus a `reason` (note required for OTHER). INITIAL is server-only and rejected here. */
    MovementRequest:
      components['schemas']['StockInOutRequest'] | components['schemas']['AdjustmentRequest'];
    StockInOutRequest: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'STOCK_IN' | 'STOCK_OUT';
      productId: string;
      /** @description Positive movement quantity (BR-12); direction derives from type. */
      quantity: number;
      note?: string;
    };
    /** @description Admin-only. Exactly one of delta / countedQuantity (BR-13). */
    AdjustmentRequest: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: 'ADJUSTMENT';
      productId: string;
      /** @description Signed, ≠ 0. Mutually exclusive with countedQuantity. */
      delta?: number;
      /** @description Absolute counted stock; the server derives the delta. Mutually exclusive with delta. */
      countedQuantity?: number;
      /** @enum {string} */
      reason: 'DAMAGED' | 'LOST' | 'FOUND' | 'COUNT_CORRECTION' | 'RETURN' | 'OTHER';
      /** @description Required when reason is OTHER. */
      note?: string;
    };
    MovementTransaction: {
      id: string;
      productId: string;
      /** @enum {string} */
      type: 'INITIAL' | 'STOCK_IN' | 'STOCK_OUT' | 'ADJUSTMENT';
      /** @description Signed net change (BR-12). */
      quantityChange: number;
      quantityAfter: number;
      userId: string;
      /** @enum {string} */
      reason?: 'DAMAGED' | 'LOST' | 'FOUND' | 'COUNT_CORRECTION' | 'RETURN' | 'OTHER';
      note?: string;
      /** Format: date-time */
      createdAt: string;
    };
    /** @description A stock-ledger row with resolved product + user labels (05 §7.6, F7). */
    TransactionRow: {
      id: string;
      /** Format: date-time */
      createdAt: string;
      productId: string;
      productName: string;
      productSku: string;
      productArchived: boolean;
      /** @enum {string} */
      type: 'INITIAL' | 'STOCK_IN' | 'STOCK_OUT' | 'ADJUSTMENT';
      quantityChange: number;
      quantityAfter: number;
      userId: string;
      userName: string;
      /** @enum {string} */
      reason?: 'DAMAGED' | 'LOST' | 'FOUND' | 'COUNT_CORRECTION' | 'RETURN' | 'OTHER';
      note?: string;
    };
    /** @description An audit-trail row — entity diff or security event (05 §7.6, F7). */
    AuditLogRow: {
      id: string;
      actorId: string;
      actorName: string;
      /** @enum {string} */
      entityType: 'PRODUCT' | 'CATEGORY' | 'USER' | 'SETTINGS' | 'SECURITY';
      entityId?: string;
      /** @description Display identity captured at write time (DN-4) — renders after hard deletes. */
      entityLabel: string;
      /** @enum {string} */
      action:
        | 'CREATE'
        | 'UPDATE'
        | 'ARCHIVE'
        | 'RESTORE'
        | 'DELETE'
        | 'LOGIN_SUCCESS'
        | 'LOGIN_FAILED'
        | 'LOCKOUT'
        | 'PASSWORD_RESET_ISSUED'
        | 'PASSWORD_RESET_COMPLETED'
        | 'PASSWORD_CHANGED'
        | 'ROLE_CHANGE'
        | 'DEACTIVATE'
        | 'REACTIVATE'
        | 'TOKEN_REUSE_DETECTED'
        | 'REPEATED_FORBIDDEN';
      changes?: {
        field: string;
        before?: unknown;
        after?: unknown;
      }[];
      ip?: string;
      /** Format: date-time */
      createdAt: string;
    };
    /** @description A low/out-of-stock preview entry linking to the product + pre-filled Stock In (FR-DASH-04). */
    DashboardAlertItem: {
      id: string;
      name: string;
      sku: string;
      quantity: number;
      lowStockThreshold: number;
    };
    /** @description One UTC day of the stock-movement trend series — in vs out (FR-DASH-02). */
    MovementTrendPoint: {
      /** @description UTC day key (YYYY-MM-DD). */
      date: string;
      in: number;
      out: number;
    };
    /** @description One UTC day of transaction volume (FR-DASH-02). */
    TransactionVolumePoint: {
      /** @description UTC day key (YYYY-MM-DD). */
      date: string;
      count: number;
    };
    /** @description The single cached dashboard aggregate (05 §7.7, FR-DASH-01…04). */
    DashboardSummary: {
      /**
       * Format: date-time
       * @description When the served snapshot was computed (may lag by ≤ TTL under cache, BR-25).
       */
      asOf: string;
      totals: {
        activeProducts: number;
        inventoryValue: components['schemas']['Money'];
        unitsInStock: number;
      };
      lowStock: {
        count: number;
        items: components['schemas']['DashboardAlertItem'][];
      };
      outOfStock: {
        count: number;
        items: components['schemas']['DashboardAlertItem'][];
      };
      /** @description The 10 most recent ledger rows (identical shape to GET /transactions). */
      recentTransactions: components['schemas']['TransactionRow'][];
      charts: {
        movementTrend: components['schemas']['MovementTrendPoint'][];
        transactionVolume: components['schemas']['TransactionVolumePoint'][];
      };
    };
    /** @description One row of the Inventory Summary report (FR-RPT-01) — line value at current cost. */
    InventoryReportRow: {
      id: string;
      sku: string;
      name: string;
      categoryName: string;
      quantity: number;
      costPrice: components['schemas']['Money'];
      lineValue: components['schemas']['Money'];
      stockStatus: components['schemas']['StockStatus'];
    };
    InventoryReport: components['schemas']['PaginationMeta'] & {
      data: components['schemas']['InventoryReportRow'][];
      totals: {
        totalQuantity: number;
        totalValue: components['schemas']['Money'];
      };
    };
    /** @description One row of the Low Stock report (FR-RPT-02) — threshold, quantity, shortage. */
    LowStockReportRow: {
      id: string;
      sku: string;
      name: string;
      categoryName: string;
      quantity: number;
      lowStockThreshold: number;
      shortage: number;
    };
    /** @description One row of the Product Performance report (FR-RPT-04) — in/out/net over the range. */
    ProductPerformanceRow: {
      productId: string;
      productSku: string;
      productName: string;
      in: number;
      out: number;
      net: number;
    };
    ProductPerformanceReport: components['schemas']['PaginationMeta'] & {
      data: components['schemas']['ProductPerformanceRow'][];
      totals: {
        totalIn: number;
        totalOut: number;
        totalNet: number;
      };
    };
    /** @description One row of the Ledger Consistency report (FR-RPT-05) — ledger sum vs quantity. */
    ConsistencyRow: {
      productId: string;
      productSku: string;
      productName: string;
      ledgerSum: number;
      quantity: number;
      drift: boolean;
    };
    /** @description The committed/replayed movement plus the resulting product state (05 §7.5). */
    MovementResponse: {
      transaction: components['schemas']['MovementTransaction'];
      product: {
        id: string;
        quantity: number;
        lowStockThreshold: number;
        stockStatus: components['schemas']['StockStatus'];
      };
    };
  };
  responses: {
    /** @description Request failed schema validation before the controller ran (05 §1). */
    ValidationError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Missing/invalid token, or account deactivated (UNAUTHORIZED | ACCOUNT_DEACTIVATED). */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Role insufficient per the §5 permission matrix (FORBIDDEN). */
    Forbidden: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Resource not found (NOT_FOUND). */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Rate limit exceeded (RATE_LIMITED, SEC-04). */
    RateLimited: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description Opaque internal error — correlation ID only, no internals (SEC-12). */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
    /** @description DB down / not ready; carries Retry-After (NFR-20). */
    ServiceUnavailable: {
      headers: {
        'Retry-After': components['headers']['RetryAfter'];
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['ErrorEnvelope'];
      };
    };
  };
  parameters: {
    /** @description 1-based page number (05 §5). */
    page: number;
    /** @description Page size — hard cap 100; values above cap → VALIDATION_ERROR (NFR-10). */
    limit: number;
    /** @description Sort field — sortable fields enumerated per endpoint; unknown → VALIDATION_ERROR. */
    sort: string;
    /** @description Sort direction companion to sort (APD-01). Default desc. */
    order: 'asc' | 'desc';
  };
  requestBodies: never;
  headers: {
    /** @description Correlation ID echoed on every response (NFR-23, 05 §1). */
    XCorrelationId: string;
    /** @description Seconds to wait before retrying (NFR-20). */
    RetryAfter: number;
  };
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Process is up. No auth, no rate limit, no business data. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthStatus'];
        };
      };
    };
  };
  getReady: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ready to serve traffic. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReadyStatus'];
        };
      };
      /** @description Not ready (DB down / booting / draining). Carries Retry-After (NFR-20). */
      503: {
        headers: {
          'Retry-After': components['headers']['RetryAfter'];
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  signup: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SignupRequest'];
      };
    };
    responses: {
      /** @description Workspace created and session established. Also sets the rotating refresh cookie (httpOnly · Secure · SameSite=Strict · Path=/api/v1/auth). */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionResponse'];
        };
      };
      400: components['responses']['ValidationError'];
      /** @description DUPLICATE_EMAIL — that email is already registered (globally unique). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      429: components['responses']['RateLimited'];
    };
  };
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Session established. Also sets the rotating refresh cookie (httpOnly · Secure · SameSite=Strict · Path=/api/v1/auth). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionResponse'];
        };
      };
      400: components['responses']['ValidationError'];
      /** @description Bad credentials (generic — UNAUTHORIZED) or ACCOUNT_DEACTIVATED. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description ACCOUNT_LOCKED — 5 consecutive failures → 15-min lock (BR-33). */
      423: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      429: components['responses']['RateLimited'];
    };
  };
  googleAuth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GoogleAuthRequest'];
      };
    };
    responses: {
      /** @description Session established. Also sets the rotating refresh cookie (httpOnly · Secure · SameSite=Strict · Path=/api/v1/auth). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionResponse'];
        };
      };
      /** @description Missing credential (VALIDATION_ERROR) or Google sign-in not configured on this server. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Invalid Google token, or the Google account email is unverified. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description DUPLICATE_EMAIL — a provisioning race on the same email. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      429: components['responses']['RateLimited'];
    };
  };
  refreshSession: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Rotated session + new refresh Set-Cookie. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionResponse'];
        };
      };
      /** @description Missing/expired/revoked/reused token (UNAUTHORIZED). */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session revoked; expired Set-Cookie returned. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['Unauthorized'];
    };
  };
  resetPassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPasswordRequest'];
      };
    };
    responses: {
      /** @description Password installed; all prior sessions revoked. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['ValidationError'];
      /** @description Invalid/expired/used token (UNAUTHORIZED). */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      429: components['responses']['RateLimited'];
    };
  };
  changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest'];
      };
    };
    responses: {
      /** @description Password changed; other sessions revoked. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['ValidationError'];
      /** @description Wrong current password, or missing/invalid access token. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  listUsers: {
    parameters: {
      query?: {
        /** @description 1-based page number (05 §5). */
        page?: components['parameters']['page'];
        /** @description Page size — hard cap 100; values above cap → VALIDATION_ERROR (NFR-10). */
        limit?: components['parameters']['limit'];
        role?: components['schemas']['Role'];
        isActive?: boolean;
        /** @description Name/email partial match, ≤ 120 chars. */
        search?: string;
        sort?: 'name' | 'email' | 'createdAt' | 'lastLoginAt';
        /** @description Sort direction companion to sort (APD-01). Default desc. */
        order?: components['parameters']['order'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List envelope of user rows. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginationMeta'] & {
            data: components['schemas']['User'][];
          };
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  createUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCreateRequest'];
      };
    };
    responses: {
      /** @description Created user (no credential fields, SEC-02). */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      /** @description DUPLICATE_EMAIL — SRS §12.2 mandated 409, unique-index-backed (race-safe). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  getOwnProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Own profile. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OwnProfile'];
        };
      };
      401: components['responses']['Unauthorized'];
    };
  };
  updateOwnProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
        };
      };
    };
    responses: {
      /** @description Updated profile (change audited). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OwnProfile'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
    };
  };
  getUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User (no credential fields). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  updateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdateRequest'];
      };
    };
    responses: {
      /** @description Updated user. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['User'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      /** @description LAST_ADMIN — the last active Admin is unviolable (BR-30). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  issueResetLink: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Reset link + expiry. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ResetLinkResponse'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  listCategories: {
    parameters: {
      query?: {
        /** @description 1-based page number (05 §5). */
        page?: components['parameters']['page'];
        /** @description Page size — hard cap 100; values above cap → VALIDATION_ERROR (NFR-10). */
        limit?: components['parameters']['limit'];
        /** @description When true, each row carries productCount (active + archived) — §9.9. */
        withCounts?: boolean;
        sort?: 'name' | 'createdAt';
        order?: 'asc' | 'desc';
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List envelope of category rows. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginationMeta'] & {
            data: components['schemas']['Category'][];
          };
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  createCategory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryWriteRequest'];
      };
    };
    responses: {
      /** @description Created category. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Category'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  getCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Category. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Category'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  deleteCategory: {
    parameters: {
      query?: {
        /** @description Target category id for bulk reassignment before delete (default UI target: Uncategorized). Identical-to-self or non-existent → VALIDATION_ERROR. */
        reassignTo?: string;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted (and reassigned, if requested). No body. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      /** @description CATEGORY_IN_USE — products still reference it; reassign first (BR-27). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  updateCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryWriteRequest'];
      };
    };
    responses: {
      /** @description Updated category. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Category'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  listProducts: {
    parameters: {
      query?: {
        /** @description 1-based page number (05 §5). */
        page?: components['parameters']['page'];
        /** @description Page size — hard cap 100; values above cap → VALIDATION_ERROR (NFR-10). */
        limit?: components['parameters']['limit'];
        /** @description Name / SKU / barcode partial match, ≤ 120 chars. */
        search?: string;
        categoryId?: string;
        stockStatus?: 'in' | 'low' | 'out';
        /** @description Admin-only — filter by archival state. Staff supplying it → 403. */
        archived?: boolean;
        sort?: 'name' | 'sku' | 'quantity' | 'createdAt' | 'costPrice';
        /** @description Sort direction companion to sort (APD-01). Default desc. */
        order?: components['parameters']['order'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List envelope of product row projections. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginationMeta'] & {
            data: components['schemas']['ProductRow'][];
          };
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  createProduct: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductCreateRequest'];
      };
    };
    responses: {
      /** @description Created product. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Product'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      /** @description DUPLICATE_SKU or DUPLICATE_BARCODE — unique-index-backed, race-safe (BR-01/05). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  lookupProduct: {
    parameters: {
      query: {
        /** @description Scanned/typed code — printable, ≤ 64 chars (BR-16). */
        code: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The matched product (scanner-facing shape). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductLookup'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
      /** @description INVALID_BARCODE — the payload is not a usable code (BR-16). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  getProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Full product. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Product'];
        };
      };
      401: components['responses']['Unauthorized'];
      404: components['responses']['NotFound'];
    };
  };
  deleteProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted. No body. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      /** @description PRODUCT_HAS_HISTORY — the product has ledger rows; archive instead (BR-23). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  updateProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductUpdateRequest'];
      };
    };
    responses: {
      /** @description Updated product (version incremented). */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Product'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      /** @description STALE_WRITE (version mismatch) or DUPLICATE_BARCODE. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  archiveProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Archived product. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Product'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      /** @description PRODUCT_NOT_EMPTY (quantity ≠ 0) or PRODUCT_ARCHIVED (already archived). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  restoreProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Restored product. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Product'];
        };
      };
      /** @description The product is not archived (VALIDATION_ERROR). */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
  recordMovement: {
    parameters: {
      query?: never;
      header: {
        /** @description RFC-4122 UUID, any version (APR-07). Missing/malformed → 400. */
        'Idempotency-Key': string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MovementRequest'];
      };
    };
    responses: {
      /** @description The committed (or replayed) movement + resulting product state. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MovementResponse'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      /** @description INSUFFICIENT_STOCK (details {available, requested}) or PRODUCT_ARCHIVED. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description IDEMPOTENCY_CONFLICT — same key, different payload (BR-20). */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  listTransactions: {
    parameters: {
      query?: {
        /** @description 1-based page number (05 §5). */
        page?: components['parameters']['page'];
        /** @description Page size — hard cap 100; values above cap → VALIDATION_ERROR (NFR-10). */
        limit?: components['parameters']['limit'];
        /** @description Inclusive start (ISO-8601 date or datetime). */
        from?: string;
        /** @description Inclusive end (a date-only value covers its whole UTC day). */
        to?: string;
        type?: 'INITIAL' | 'STOCK_IN' | 'STOCK_OUT' | 'ADJUSTMENT';
        productId?: string;
        userId?: string;
        /** @description Include rows whose product is archived (default false). */
        includeArchived?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List envelope of ledger rows. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginationMeta'] & {
            data: components['schemas']['TransactionRow'][];
          };
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  listAuditLogs: {
    parameters: {
      query?: {
        /** @description 1-based page number (05 §5). */
        page?: components['parameters']['page'];
        /** @description Page size — hard cap 100; values above cap → VALIDATION_ERROR (NFR-10). */
        limit?: components['parameters']['limit'];
        entityType?: 'PRODUCT' | 'CATEGORY' | 'USER' | 'SETTINGS' | 'SECURITY';
        entityId?: string;
        actorId?: string;
        from?: string;
        to?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List envelope of audit rows. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginationMeta'] & {
            data: components['schemas']['AuditLogRow'][];
          };
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  getDashboardSummary: {
    parameters: {
      query?: {
        /** @description Chart/trend window in days (FR-DASH-02). Default 30. */
        range?: 7 | 30 | 90;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The dashboard summary snapshot. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DashboardSummary'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  getInventoryReport: {
    parameters: {
      query?: {
        /** @description 1-based page number (05 §5). */
        page?: components['parameters']['page'];
        /** @description Page size — hard cap 100; values above cap → VALIDATION_ERROR (NFR-10). */
        limit?: components['parameters']['limit'];
        categoryId?: string;
        stockStatus?: components['schemas']['StockStatus'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Inventory rows + totals. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InventoryReport'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  getLowStockReport: {
    parameters: {
      query?: {
        /** @description 1-based page number (05 §5). */
        page?: components['parameters']['page'];
        /** @description Page size — hard cap 100; values above cap → VALIDATION_ERROR (NFR-10). */
        limit?: components['parameters']['limit'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Low-stock rows. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginationMeta'] & {
            data: components['schemas']['LowStockReportRow'][];
          };
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  getTransactionsReport: {
    parameters: {
      query: {
        /** @description 1-based page number (05 §5). */
        page?: components['parameters']['page'];
        /** @description Page size — hard cap 100; values above cap → VALIDATION_ERROR (NFR-10). */
        limit?: components['parameters']['limit'];
        from: string;
        to: string;
        type?: 'INITIAL' | 'STOCK_IN' | 'STOCK_OUT' | 'ADJUSTMENT';
        productId?: string;
        userId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ledger rows over the range. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginationMeta'] & {
            data: components['schemas']['TransactionRow'][];
          };
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  getProductPerformanceReport: {
    parameters: {
      query: {
        /** @description 1-based page number (05 §5). */
        page?: components['parameters']['page'];
        /** @description Page size — hard cap 100; values above cap → VALIDATION_ERROR (NFR-10). */
        limit?: components['parameters']['limit'];
        from: string;
        to: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Per-product performance rows + totals. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductPerformanceReport'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  getConsistencyReport: {
    parameters: {
      query?: {
        /** @description 1-based page number (05 §5). */
        page?: components['parameters']['page'];
        /** @description Page size — hard cap 100; values above cap → VALIDATION_ERROR (NFR-10). */
        limit?: components['parameters']['limit'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Consistency rows. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginationMeta'] & {
            data: components['schemas']['ConsistencyRow'][];
          };
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  exportReport: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        name: 'inventory' | 'low-stock' | 'transactions' | 'product-performance' | 'consistency';
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description CSV stream of the full filtered dataset. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/csv': string;
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  getSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The settings singleton. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Settings'];
        };
      };
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  updateSettings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SettingsUpdateRequest'];
      };
    };
    responses: {
      /** @description Updated settings. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Settings'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  createUploadSignature: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UploadSignatureRequest'];
      };
    };
    responses: {
      /** @description Signed upload parameters. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UploadSignatureResponse'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
    };
  };
  destroyUpload: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Percent-encoded Cloudinary publicId (e.g. ims%2Fprod%2Fabc123). */
        publicId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Destroyed. No body. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components['responses']['Unauthorized'];
      /** @description FORBIDDEN — the publicId is outside the app's upload folder (APR-03). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      404: components['responses']['NotFound'];
    };
  };
  askAssistant: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatAskRequest'];
      };
    };
    responses: {
      /** @description The answer, discriminated on `intent`. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ChatResponse'];
        };
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
      429: components['responses']['RateLimited'];
      503: components['responses']['ServiceUnavailable'];
    };
  };
  rateAssistantAnswer: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChatFeedbackRequest'];
      };
    };
    responses: {
      /** @description Recorded. No body. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components['responses']['ValidationError'];
      401: components['responses']['Unauthorized'];
      403: components['responses']['Forbidden'];
      404: components['responses']['NotFound'];
    };
  };
}
